### ISSUE TITLE
Hi , Can you provide detailed

### ISSUE THREAD

**Issue by bidyashish** [SidharthRaveendran/Attendance#1]
Hi ,   
I am building student   EXAMS FORMS for student 
AND    staff  admin to verify forms 

so can  you  let  me know detailed explanation

**Comment by SidharthRaveendran** [comment]
This project has seperate logins for Staff and Student.

The staff can

CRUD Students
CRUD Departments
CRUD Attendance for the students

The student can only see his attendance after logging into the application.

You can add an extra CRUD for the exam form.
